# Generated by Django 5.1.1 on 2024-09-19 22:21

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_empleado_avatar_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=django_quill.fields.QuillField(default='texto'),
            preserve_default=False,
        ),
    ]
