# Generated by Django 5.1.1 on 2024-09-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_pruebas_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
