# Generated by Django 5.1.1 on 2024-09-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_prueba_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='finalizado',
        ),
    ]
